/**
 * Brawl Mode taglines — draft reference for on-card display.
 *
 * Rules:
 *   - Max ~28 characters; one line; HP-relevant only in brawl.
 *   - pool "in"  = signature (always dealt via dealHand)
 *   - pool "gen" = curated general pool (2 random per hand in brawl)
 *   - pool "out" = excluded from brawl general pool
 *   - remap      = brawl should use simplified effect (not just tagline)
 */
export const BRAWL_TAGLINE_DRAFT = {
  "b-1":  { tagline: "+4 if chained",                    pool: "in" },
  "b-2":  { tagline: "−2 their top solo",               pool: "in" },
  "b-3":  { tagline: "□/◆ only · +3 chained",           pool: "in" },
  "b-4":  { tagline: "Solo · high power",               pool: "in" },
  "b-5":  { tagline: "Swap all your shapes",            pool: "in", remap: "Keep shape-swap OR brawl: +3 if chained" },
  "b-6":  { tagline: "+3 if chained",                    pool: "in", remap: "Hit Scale → flat +3 chained in brawl" },
  "b-7":  { tagline: "+3 if chained",                    pool: "in", remap: "Reveal → removed in brawl" },
  "b-8":  { tagline: "+3 to your top solo",              pool: "in" },
  "b-9":  { tagline: "Immune to debuffs",               pool: "in" },
  "b-10": { tagline: "Both edges wild",                 pool: "in" },
  "b-11": { tagline: "+4 if solo",                      pool: "in", remap: "Auto-single → +4 solo bonus in brawl" },
  "b-12": { tagline: "Left edge wild",                  pool: "in", remap: "Shape-pick modal → left wild in brawl" },
  "b-13": { tagline: "+4 first AB of inning",           pool: "in" },
  "b-14": { tagline: "+3 if linked to □",               pool: "in" },
  "b-15": { tagline: "Left edge wild",                  pool: "in" },
  "b-16": { tagline: "+4 if linked to ◆",               pool: "in" },
  "b-17": { tagline: "Their chains −2 total",           pool: "in" },
  "b-18": { tagline: "+4 if chained",                   pool: "in", remap: "Hit Scale → +4 chained in brawl" },
  "b-19": { tagline: "+5 with 2 outs",                  pool: "in" },
  "b-20": { tagline: "12 if sandwiched",                pool: "in" },
  "b-21": { tagline: "−2 their general",                pool: "in", remap: "Destroy → −2 one general in brawl" },
  "b-22": { tagline: "+3 if chained",                   pool: "in", remap: "Coin flip → flat +3 chained" },
  "b-23": { tagline: "Their generals −1 each",          pool: "in", remap: "Silence generals → −1 each" },
  "b-24": { tagline: "● links only",                    pool: "in" },
  "b-25": { tagline: "+2 per solo card left",           pool: "in" },
  "b-26": { tagline: "+4 on right link",                pool: "in" },
  "b-27": { tagline: "+3 vs fastball ace",              pool: "in" },
  "b-28": { tagline: "No link on left",                 pool: "in" },
  "b-29": { tagline: "+1 per ● on board",               pool: "in" },
  "b-30": { tagline: "Halve their ace",                 pool: "in" },
  "b-100": { tagline: "+5 chained vs fastball",         pool: "in" },
  "b-101": { tagline: "+1 per vet in their hand",      pool: "in" },
  "b-102": { tagline: "No link on right",               pool: "in" },
  "b-103": { tagline: "+1 per ◆ on board",              pool: "in" },
  "b-104": { tagline: "+3 with 0 outs",                 pool: "in" },
  "b-105": { tagline: "Blank their ace ability",        pool: "in" },
  "b-106": { tagline: "14 if chained",                  pool: "in" },
  "b-107": { tagline: "+2 per power in hand",           pool: "in" },
  "b-108": { tagline: "Their off-speed silenced",       pool: "in" },
  "b-109": { tagline: "+3 in inning 3",                pool: "in", remap: "4th+ inning → inning 3 in brawl" },
  "b-110": { tagline: "+4 on left link",                pool: "in" },
  "b-111": { tagline: "+5 if score tied",               pool: "in" },
  "b-112": { tagline: "+2 per shape (max +6)",          pool: "in" },
  "b-113": { tagline: "+1 per card chained",            pool: "in" },
  "b-114": { tagline: "+3 speed+power in hand",        pool: "in" },
  "b-115": { tagline: "+1 per ★ on board",              pool: "in" },
  "b-116": { tagline: "+3 if chained",                 pool: "in", remap: "Hit Scale → +3 chained" },
  "b-117": { tagline: "+2 if chained",                 pool: "in", remap: "Hit Scale → +2 chained" },
  "b-118": { tagline: "+5 with no chains",             pool: "in" },
  "b-119": { tagline: "Their generals −2 each",         pool: "in" },
  "b-120": { tagline: "+3 if chained",                  pool: "in", remap: "Extra bases → +3 chained win" },
  "b-121": { tagline: "+3 vs breaking ace",             pool: "in", remap: "Reveal → matchup hook" },
  "b-122": { tagline: "+5 vs breaking ace",            pool: "in" },
  "b-123": { tagline: "+1 to each other card",          pool: "in" },
  "b-124": { tagline: "+6 if sandwiched",               pool: "in" },
  "b-125": { tagline: "Your ◆ edges wild",              pool: "in" },
  "b-126": { tagline: "+3 vs RHP",                     pool: "in" },
  "b-127": { tagline: "− their lowest solo",            pool: "in" },
  "b-128": { tagline: "+2 vs lefty pitcher",           pool: "in", remap: "Hit Scale → +2 vs lefty" },
  "b-129": { tagline: "+1 per solo left",               pool: "in" },
  "b-130": { tagline: "+5 losing or tied",              pool: "in" },
  "b-131": { tagline: "+3 with 2+ clutch cards",       pool: "in" },
  "b-132": { tagline: "+1 per run you've scored",       pool: "in" },
  "b-133": { tagline: "Solo · both edges wild",         pool: "in" },
  "b-134": { tagline: "+3 if solo",                     pool: "in", remap: "Hit Scale → +3 solo" },
  "b-135": { tagline: "+3 if you win",                  pool: "in", remap: "Extra runner → +3 win bonus" },
  "b-61": { tagline: "□/◆ links only",                  pool: "gen" },
  "b-62": { tagline: "+2 if chained",                   pool: "gen" },
  "b-64": { tagline: "+4 vs fastball",                  pool: "gen" },
  "b-68": { tagline: "Left edge wild",                  pool: "gen" },
  "b-71": { tagline: "You win ties",                    pool: "gen" },
  "b-72": { tagline: "+1 per clutch in hand",           pool: "gen" },
  "b-74": { tagline: "+1 per vet in hand",              pool: "gen" },
  "b-75": { tagline: "+5 with rookie in hand",          pool: "gen" },
  "b-76": { tagline: "+3 chained w/ power",             pool: "gen" },
  "b-77": { tagline: "+5 vs closer",                    pool: "gen" },
  "b-78": { tagline: "−2 vs starter",                   pool: "gen" },
  "b-79": { tagline: "+4 vs lefty",                     pool: "gen" },
  "b-80": { tagline: "+3 vs off-speed",                 pool: "gen" },
  "b-81": { tagline: "+6 if ◆ sandwich",               pool: "gen" },
  "b-83": { tagline: "+8 if chain ≥3",                 pool: "gen" },
  "b-84": { tagline: "+8 if chain ≥4",                 pool: "gen" },
  "b-85": { tagline: "+1 per card right in chain",     pool: "gen" },
  "b-86": { tagline: "+5 leftmost slot",                pool: "gen" },
  "b-87": { tagline: "+5 as 4th card",                 pool: "gen" },
  "b-88": { tagline: "+3 solo · last slot",            pool: "gen" },
  "b-93": { tagline: "+4 if losing",                   pool: "gen" },
  "b-94": { tagline: "+2 if leading",                  pool: "gen" },
  "b-95": { tagline: "+4 in inning 3",                 pool: "gen", remap: "7th+ → inning 3" },
  "b-96": { tagline: "+2 bottom of inning",            pool: "gen" },
  "b-63": { tagline: "+2 if chained",                   pool: "out", remap: "Hit cap removed" },
  "b-65": { tagline: "+3 if chained",                   pool: "out", remap: "Shape-pick modal" },
  "b-66": { tagline: "+2 if chained",                   pool: "out", remap: "Hit Scale" },
  "b-67": { tagline: "—",                               pool: "out", remap: "Discard/redraw" },
  "b-69": { tagline: "—",                               pool: "out", remap: "Base-running" },
  "b-70": { tagline: "—",                               pool: "out", remap: "Hit Scale" },
  "b-73": { tagline: "—",                               pool: "out", remap: "Hit Scale" },
  "b-82": { tagline: "—",                               pool: "out", remap: "Sequence puzzle" },
  "b-91": { tagline: "—",                               pool: "out", remap: "Base state" },
  "b-92": { tagline: "—",                               pool: "out", remap: "Base state" },
  "p-31": { tagline: "They can't use wilds",             pool: "in" },
  "p-32": { tagline: "Solo · +2 alone",                pool: "in" },
  "p-33": { tagline: "−3 from their total",             pool: "in", remap: "Hit Scale shrink → −3 HP debuff" },
  "p-34": { tagline: "+3 on right link",                pool: "in" },
  "p-35": { tagline: "They can't link □",               pool: "in" },
  "p-36": { tagline: "Blank their top card",            pool: "in" },
  "p-37": { tagline: "+2 vs lefty batter",              pool: "in" },
  "p-38": { tagline: "−3 batter if chained",           pool: "in" },
  "p-39": { tagline: "−2 their general",               pool: "in", remap: "Force discard → −2 general" },
  "p-40": { tagline: "+1 per card they chain",          pool: "in" },
  "p-41": { tagline: "−4 if they chain 2+",             pool: "in", remap: "Break link modal → auto −4" },
  "p-42": { tagline: "Their bases capped at 6",         pool: "in" },
  "p-43": { tagline: "Solo · flat edges",               pool: "in" },
  "p-44": { tagline: "+3 if you win",                  pool: "in", remap: "2 outs → win bonus" },
  "p-45": { tagline: "+5 in inning 3",                  pool: "in", remap: "9th inning → inning 3" },
  "p-46": { tagline: "+2 with no chains",              pool: "in" },
  "p-47": { tagline: "Their ◆ go flat",                 pool: "in" },
  "p-48": { tagline: "You win ties",                    pool: "in" },
  "p-49": { tagline: "Their shapes swap",               pool: "in" },
  "p-50": { tagline: "−6 if they chain 3+",            pool: "in" },
  "p-51": { tagline: "+3 if chained",                   pool: "in", remap: "Reveal → +3 chained" },
  "p-52": { tagline: "−3 their top solo",              pool: "in" },
  "p-53": { tagline: "Match their best chain",          pool: "in", remap: "Keep OR cap at +8 over base" },
  "p-54": { tagline: "+2 if solo",                     pool: "in", remap: "Extra draw → +2 solo" },
  "p-55": { tagline: "+3 on left link",                pool: "in" },
  "p-56": { tagline: "+3 if chained",                   pool: "in", remap: "Shape-pick → +3 chained OR auto-best" },
  "p-57": { tagline: "+4 vs all solos",                 pool: "in" },
  "p-58": { tagline: "+3 if win by 6+",                pool: "in", remap: "Next-batter debuff → win margin" },
  "p-59": { tagline: "+3 if chained",                   pool: "in", remap: "Force reveal → removed" },
  "p-60": { tagline: "−1 per □ they play",             pool: "in" },
  "p-71": { tagline: "+1 if solo",                      pool: "gen" },
  "p-72": { tagline: "−3 batter if ◆ link",           pool: "gen" },
  "p-73": { tagline: "+3 w/ fastball in chain",         pool: "gen" },
  "p-74": { tagline: "+1 per ● they play",             pool: "gen" },
  "p-76": { tagline: "+2 to your top solo",            pool: "gen" },
  "p-80": { tagline: "You win ties",                    pool: "gen" },
  "p-81": { tagline: "+2 w/ breaking ball",            pool: "gen" },
  "p-82": { tagline: "+3 w/ fastball in chain",         pool: "gen" },
  "p-83": { tagline: "+1 per □ they play",             pool: "gen" },
  "p-84": { tagline: "+2 if solo",                     pool: "gen" },
  "p-85": { tagline: "+4 w/ closer in hand",           pool: "gen" },
  "p-86": { tagline: "+1 per vet in hand",             pool: "gen" },
  "p-87": { tagline: "+3 w/ rookie in hand",           pool: "gen" },
  "p-89": { tagline: "+4 vs lefty batter",             pool: "gen" },
  "p-90": { tagline: "−3 vs power hitter",             pool: "gen" },
  "p-91": { tagline: "+3 bases empty",                 pool: "gen" },
  "p-92": { tagline: "+4 with 2+ runners",             pool: "gen" },
  "p-93": { tagline: "+5 lead ≤3 runs",                pool: "gen" },
  "p-94": { tagline: "+3 in inning 3",                 pool: "gen", remap: "8th+ → inning 3" },
  "p-96": { tagline: "+2 per □↔◆ alternation",        pool: "gen" },
  "p-75": { tagline: "—",                               pool: "out", remap: "Runner removal" },
  "p-77": { tagline: "—",                               pool: "out", remap: "Swap card" },
  "p-78": { tagline: "—",                               pool: "out", remap: "Star nullify niche" },
  "p-79": { tagline: "—",                               pool: "out", remap: "Skip at-bat" },
  "p-88": { tagline: "—",                               pool: "out", remap: "Hit Scale wall" },
  "p-95": { tagline: "—",                               pool: "out", remap: "Palindrome check" },
} as const;

export const BRAWL_GENERAL_POOL = [
  "b-61","b-62","b-64","b-68","b-71","b-72","b-74","b-75","b-76","b-77",
  "b-78","b-79","b-80","b-81","b-83","b-84","b-85","b-86","b-87","b-88",
  "b-93","b-94","b-95","b-96",
  "p-71","p-72","p-73","p-74","p-76","p-80","p-81","p-82","p-83","p-84",
  "p-85","p-86","p-87","p-89","p-90","p-91","p-92","p-93","p-94","p-96",
] as const;

export const BRAWL_GENERAL_POOL_EXCLUDED = [
  "b-63","b-65","b-66","b-67","b-69","b-70","b-73","b-82","b-91","b-92",
  "p-75","p-77","p-78","p-79","p-88","p-95",
] as const;
